version: "3"
services:
  api:
    container_name: saso-backend
    image: index.docker.io/iwkz/saso-backend:latest
    env_file:
      - .env.backend
    networks:
      - saso_net
    depends_on:
      - db
    ports:
      - "3000:3000"
      
  db:
    container_name: mongo
    image: mongo:4.2.0-bionic
    volumes:
      - /data/db:/data/db
    env_file:
      - .env.db
    networks:
      - saso_net
    ports:
      - "27017:27017"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: --interval 30
networks:
  saso_net:
    driver: bridge